Repository abg287/Balanced, pull requests merged in 2024-10, with the labels that each got.

#22 Route pages
  .env
  .gitignore
  README.md
  app.js
  package.json
  src/client/components/AddMeal.jsx
  src/client/components/Header.jsx
  src/client/components/Home.jsx
  src/client/components/Layout.jsx
  src/client/components/PhysicalData.jsx
  src/client/components/Recommendations.jsx
  src/client/components/SideBar.jsx
  src/client/components/foodFinder.py
  src/client/components/foodStorer.py
  src/client/components/mongoConnector.py
  src/client/hooks/useFetch.js
  src/client/index.jsx
  src/client/pictures/logo.png
  src/client/public/index.css
  src/client/public/index.html
  src/components/App.jsx
  src/components/Header.jsx
  src/components/MainPage.jsx
  src/components/page_components/ApplicationHome.jsx
  src/components/page_components/SideBar.jsx
  src/index.js
  src/server.js
  webpack.config.cjs
Labels: enhancement

#24 implemented adding food form with form validation and capability to send data to database
  package.json
  src/client/components/AddFood.jsx
  src/client/components/AddMeal.jsx
  src/client/components/SideBar.jsx
  src/client/index.jsx
  src/client/public/index.css
  src/models.js
  src/schemas.js
  src/server.js
Labels: enhancement

#35 Fixed bug preventing server from starting
  src/client/components/AddFood.jsx
Labels: bug

#37 Delete foods
  src/client/components/Food.jsx
  src/client/components/Home.jsx
  src/server.js
Labels: enhancement

#38 Added CSS for Home.jsx
  src/client/components/Food.jsx
  src/client/components/Home.jsx
  src/client/public/index.css
Labels: enhancement

#40 applied css
  src/client/components/PhysicalData.jsx
  src/client/public/index.css
Labels: enhancement

#47 Unittests
  babel.config.cjs
  jest.config.cjs
  package.json
  src/client/components/AddFood.jsx
  src/client/components/PhysicalData.jsx
  src/tests/AddFood.test.jsx
  src/tests/PhysicalData.test.jsx
Labels: documentation
